#########################################################################################################
#                                             uCOS XSDK BSP
#
#                    Copyright 2014-2020 Silicon Laboratories Inc. www.silabs.com
#
#                                 SPDX-License-Identifier: APACHE-2.0
#
#               This software is subject to an open source license and is distributed by
#                Silicon Laboratories Inc. pursuant to the terms of the Apache License,
#                    Version 2.0 available at www.apache.org/licenses/LICENSE-2.0.
#
#########################################################################################################

ARCH_LIBSOURCES:=mb/ucos_impl.c \
                 mb/ucos_int_impl.c

ARCH_INCLUDEFILES:=mb/ucos_int_impl.h \
                   mb/ucos_impl.h