#########################################################################################################
#                                             uCOS XSDK BSP
#
#                    Copyright 2014-2020 Silicon Laboratories Inc. www.silabs.com
#
#                                 SPDX-License-Identifier: APACHE-2.0
#
#               This software is subject to an open source license and is distributed by
#                Silicon Laboratories Inc. pursuant to the terms of the Apache License,
#                    Version 2.0 available at www.apache.org/licenses/LICENSE-2.0.
#
#########################################################################################################


ARCH_LIBSOURCES:= psua53/ucos_impl.c \
                  psua53/ucos_int_impl.c \
                  psua53/ucos_vectors.S


ARCH_INCLUDEFILES:=psua53/ucos_int_impl.h \
                   psua53/ucos_impl.h
